### PR TITLE
Ensure that public headers are prefixed with 'InfluxDB".

### PR DESCRIPTION
**Pull request by BillyONeal**
In vcpkg's registry, before https://github.com/microsoft/vcpkg-tool/pull/1483 , we missed that `influxdb-cxx` conflicts with `libproxy`, because the former spells the header `include/Proxy.h` while the latter spells it `include/proxy.h`. This caused the ports to silently damage each other on case insensitive file systems, such as on Windows and macOS.

Given that the names "Proxy.h", "Transport.h", and "Point.h" are all extremely likely to conflict with other users, and `influxdb-cxx` already seems to have  a convention for header names to be prefixed with "InfluxDB", we, the vcpkg registry maintainers, believe it would be best if these headers were renamed to resolve the conflict.

### CODE REVIEW

**Comment by offa** [comment]
:see_no_evil: Oh dear …

Thank you for reporting.

I would suggest moving the files to a subdirectory called "include/InfluxDB/" instead of renaming them. The CMake files will also be installed in a similar subdirectory.

**Comment by BillyONeal** [comment]
> I would suggest moving the files to a subdirectory called "include/InfluxDB/" instead of renaming them. The CMake files are installed in a similar subdirectory already.

That would also work 👍. I'm less confident in making that change correctly myself :/

**Comment by offa** [comment]
No problem, I'll take care of it.

**Comment by offa** [comment]
Could you give #264 a try?

**Comment by BillyONeal** [comment]
Obsoleted by https://github.com/offa/influxdb-cxx/pull/264

**Pull request closed without merging**
