### PR TITLE
fix: conan create package

### PR DESCRIPTION
**Pull request by steinerthomas**
Creating the package with conan failed because the cmake finder couln't find CURL.
`conan create . influxdb-cxx/0.6.4@steiner/testing -o shared=True -o libcurl:shared=True -o openssl:shared=True -o zlib:shared=True -o boost=False`
```
CMake Error at /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find CURL (missing: CURL_LIBRARY CURL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.18/Modules/FindCURL.cmake:169 (find_package_handle_standard_args)
  CMakeLists.txt:74 (find_package)


-- Configuring incomplete, errors occurred!
```
We can use the [cmake_find_package generator](https://blog.conan.io/2018/06/11/Transparent-CMake-Integration.html) here and conan create will work.

### CODE REVIEW

**Comment by offa** [comment]
This is an interesting behaviour as the CI build still builds the package without running into the issue (boost on/off). I'm also able to build it locally.

Here's how my minimal build:

```
conan create .
```

When building shared using your options – please note the 'influxdb-cxx:' prefix I had to use – I'm getting undefined reference issues on the conan test package step though. The package build was able to pick up curl.

```
conan create  -o influxdb-cxx:shared=True -o libcurl:shared=True -o openssl:shared=True -o zlib:shared=True -o influxdb-cxx:boost=False .
```

What happens if you build without the shared options?

**Comment by offa** [comment]
I have just noticed, that the package build seems to pick up my systems curl instead :facepalm:. Can you check the CMake log whether this happens to you as well?

**Comment by offa** [comment]
I have tested the change locally and it solves curl issue. But building without the shared flags fails:

```
> conan create .
[…]
-- Library boost_system found […long conan path…]/libboost_system.so
-- Found: […long conan path…]/libboost_system.so
[…]
CMake Error at src/CMakeLists.txt:1 (add_library):
  Target "InfluxDB" links to target "Boost::system" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at src/CMakeLists.txt:1 (add_library):
  Target "InfluxDB" links to target "Boost::system" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
[…]
```

**Comment by steinerthomas** [comment]
> I have tested the change locally and it solves curl issue. But building without the shared flags fails:
> 
> ```
> > conan create .
> […]
> -- Library boost_system found […long conan path…]/libboost_system.so
> -- Found: […long conan path…]/libboost_system.so
> […]
> CMake Error at src/CMakeLists.txt:1 (add_library):
>   Target "InfluxDB" links to target "Boost::system" but the target was not
>   found.  Perhaps a find_package() call is missing for an IMPORTED target, or
>   an ALIAS target is missing?
> 
> 
> CMake Error at src/CMakeLists.txt:1 (add_library):
>   Target "InfluxDB" links to target "Boost::system" but the target was not
>   found.  Perhaps a find_package() call is missing for an IMPORTED target, or
>   an ALIAS target is missing?
> […]
> ```

boost in conan-center-index is not supporting [components](https://github.com/conan-io/conan/issues/6863) yet, so i removed the find_package_generator and used the cmake generator instead.

**Comment by steinerthomas** [comment]
> This is an interesting behaviour as the CI build still builds the package without running into the issue (boost on/off). I'm also able to build it locally.
> 
> Here's how my minimal build:
> 
> ```
> conan create .
> ```
> 
> When building shared using your options – please note the 'influxdb-cxx:' prefix I had to use – I'm getting undefined reference issues on the conan test package step though. The package build was able to pick up curl.
> 
> ```
> conan create  -o influxdb-cxx:shared=True -o libcurl:shared=True -o openssl:shared=True -o zlib:shared=True -o influxdb-cxx:boost=False .
> ```
> 
> What happens if you build without the shared options?

Sry, I didn't test that before. I only cross-compiled to another target and skipped the test_pacakge with -tf None. 
With the cmake generator it is working now.

**Comment by offa** [comment]
Thank you! :+1: 

To be honest, I don't really understand why this variant works, even though the components aren't supported by boost …

**Pull request merged**
