### PR TITLE
Restore compatibility with archived upstream project

### PR DESCRIPTION
**Pull request by fmoessbauer**

### CODE REVIEW

**Comment by offa** [comment]
Thanks! :+1: It turned out, merging a pending upstream pr introduced the API change.

I don't have a strong opinion on what version of flush() should be deprecated. Or, should a more general `flush()` replace both?

The wrong cmake variable is my fault though :man_facepalming:.

**Comment by offa** [comment]
Since it's a C++17 project, we can use the *deprecated* attribute to make it more visible.

**Comment by offa** [comment]
I'm going to create a new release with this PR. Thanks again for fixing the broken API.

**Comment by fmoessbauer** [comment]
> I'm going to create a new release with this PR. Thanks again for fixing the broken API.

Thanks! IMO the generic `flush()` would be best candidate, but to be backwards compatible with the last release we would then need two aliases. So I vote for just keeping the current one and maybe adding the `[[deprecated]]` attribute.

The only thing that bogs me is that for `[[deprecated]]` we would need at least icc18, while for many other cpp17 features icc17 is sufficient (I don't think the project uses something that requires icc18).
https://en.cppreference.com/w/cpp/compiler_support

**Comment by offa** [comment]
Yes, you are right. I'll add the attribute, but for now leave the methods as they are.

**Pull request merged**
